[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "slack-agent"
version = "0.1.0"
description = "Your project description"
readme = "README.md"
authors = [
    {name = "sushovong", email = "sushovon.ghosh@udaan.com"}
]
requires-python = ">=3.8"
dependencies = [
    "flask>=3.0.3",
    "python-dotenv>=1.0.1",
    "requests>=2.32.4",
    "slack-sdk>=3.36.0",
    "werkzeug>=3.0.0",
]
