project: slack-agent
version: '1.0'

server:
  applicationConnectors:
  - type: http
    port: 5000

kubernetes:
  cpus: 0.1
  mem: 256
  healthcheck: "none"
  containerSpec:
    envFrom:
      - secretRef:
          name: slack-agent
